<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lef_responsive_images"
 *
 * Auto generated by Extension Builder 2015-03-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
  'title' => 'Bootstrap3 responsive images',
  'description' => 'Extends the bootstrap_package 
auto generate image at the right size
include support for retina',
  'category' => 'fe',
  'author' => 'Stephen Leger',
  'author_email' => 'stephen@3dservices.ch',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.3',
  'constraints' => array(
    'depends' => array(
      'typo3' => '6.2.0-7.1.99',
      'bootstrap_package' => '6.2.0-7.1.99',
    ),
    'conflicts' => array(
      'themes' => '2.3.0',
    ),
    'suggests' => array(
    ),
  ),
);