<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lef_responsive_images"
 *
 * Auto generated by Extension Builder 2015-03-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
  'title' => 'Bootstrap3 responsive images',
  'description' => 'Extends the bootstrap_package 
auto generate images at the right size
add support for 1 to 10 columns for images
add css background and art direction images
extends carousel to use responsive background
  ',
  'category' => 'template',
  'author' => 'Stephen Leger',
  'author_email' => 'stephen@3dservices.ch',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.0.8',
  'autoload' => 
  array (
    'psr-4' => 
    array (
      'LEF\\LefResponsiveImages\\' => 'Classes',
    ),
  ),
  'constraints' => array(
    'depends' => array(
      'typo3' => '7.6.0-8.6.99',
      'bootstrap_package' => '7.6.0-8.6.99',
    ),
    'conflicts' => array(
      'themes' => '*',
    ),
    'suggests' => array(
    ),
  ),
);